MVC/Models/ErrorViewModel.cs
namespace MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Models;
using System.Diagnostics;

namespace MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewBag.url = ApiEndpoints.SwaggerUrl;
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC/Controllers/MasaController.cs
using Common.Requests.Masa;
using Common.Requests.Musteri;
using Common.Requests.Siparis;
using Domain.masa;
using Domain.menu;
using Domain.musteri;
using Domain.odemeturu;
using Domain.personel;
using Domain.siparis;
using Microsoft.AspNetCore.Mvc;

namespace MVC.Controllers
{
    public class MasaController : Controller
    {
        private readonly ApiRequestHelper _apiRequestHelper;

        public MasaController(ApiRequestHelper apiRequestHelper)
        {
            _apiRequestHelper = apiRequestHelper;
        }

        // GET: MasaController
        public async Task<ActionResult> Index(int page = 1)
        {
            int pageSize = 16;
            int totalMasalar = 0;
            int totalPages = 0;
            var result = await _apiRequestHelper.GetAsync<IEnumerable<Masa>>(ApiEndpoints.MasaControllerGetUrl);
            if (result != null)
            {
                totalMasalar = result.Count();
                totalPages = (int)Math.Ceiling((double)totalMasalar / pageSize); 
                result = result.OrderBy(r => r.MasaNo);
                result = result.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            }
            ViewBag.CurrentPage = page;
            ViewBag.TotalPages = totalPages;

            return View(result);
        }

        // GET: MasaController/Details/5
        public async Task<ActionResult> Details(Guid id)
        {
            var result = await _apiRequestHelper.GetAsync<Masa>(ApiEndpoints.MasaControllerGetByIdUrl + id);
            return View(result);
        }

        // GET: MasaController/Create
        public ActionResult _Create()
        {
            return View();
        }

        // POST: MasaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateMasaRequest masa)
        {

            await _apiRequestHelper.PostAsync<CreateMasaRequest>(masa, ApiEndpoints.MasaControllerCreateUrl);
            return RedirectToAction("Index");
        }

        // GET: MasaController/Edit/5
        public async Task<ActionResult> _EditAsync(Guid id)
        {
            var result = await _apiRequestHelper.GetAsync<Masa>(ApiEndpoints.MasaControllerGetByIdUrl + id);
            return View(result);
        }

        // POST: MasaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditAsync(UpdateMasaRequest masa)
        {
            await _apiRequestHelper.PutAsync(masa, ApiEndpoints.MasaControllerUpdateUrl + masa.Id);
            return RedirectToAction(nameof(Index));
        }

        // GET: MasaController/Delete/5
        public async Task<ActionResult> _DeleteAsync(Guid id)
        {
            await DeleteAsync(id);
            return RedirectToAction("Index");
        }

        // POST: MasaController/Delete/5
        [HttpDelete]
        [ValidateAntiForgeryToken]
        public async Task DeleteAsync(Guid id)
        {
            await _apiRequestHelper.DeleteAsync(ApiEndpoints.MasaControllerDeleteUrl + id);
        }

        [HttpGet]
        public async Task<IActionResult> _SiparisEkle(Guid id)
        {
            var masa = await _apiRequestHelper.GetAsync<Masa>(ApiEndpoints.MasaControllerGetByIdUrl + id);
            var personeller = await _apiRequestHelper.GetAsync<List<Personel>>(ApiEndpoints.PersonelControllerGetUrl);
            var musteriler = await _apiRequestHelper.GetAsync<List<Musteri>>(ApiEndpoints.MusteriControllerGetUrl);
            var menuler = await _apiRequestHelper.GetAsync<List<Menu>>(ApiEndpoints.MenuControllerGetUrl);
            ViewBag.Personeller = personeller;
            ViewBag.Musteriler = musteriler;
            ViewBag.Menuler = menuler;
            return PartialView("_siparisEkle", masa); 
        }

        [HttpPost]
        public async Task<IActionResult> CreateSiparis(CreateSiparisRequest request)
        {
            if (ModelState.IsValid)
            {
                await _apiRequestHelper.PostAsync(request, ApiEndpoints.SiparisControllerCreateUrl);   
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult _MusteriEkle()
        {
            return PartialView("_musteriEkle");
        }

        [HttpPost]
        public async Task<IActionResult> CreateMusteri(CreateMusteriRequest musteri)
        {
            if (ModelState.IsValid)
            {
                await _apiRequestHelper.PostAsync(musteri, ApiEndpoints.MusteriControllerCreateUrl);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> _OdemeYap(Guid id)
        {
            var siparis = await _apiRequestHelper.GetAsync<Siparis>(ApiEndpoints.SiparisControllerGetSiparisByMasaIdUrl + id);
            var odemeTipleri = await _apiRequestHelper.GetAsync<List<OdemeTuru>>(ApiEndpoints.OdemeTuruControllerGetUrl);
            ViewBag.OdemeTipleri = odemeTipleri;
            return PartialView("_OdemeYap", siparis.SiparisDetaylar);
        }

        [HttpPost]
        public async Task<IActionResult> OdemeYap(List<Guid> SelectedSiparisDetaylarIdList, Guid OdemeTipiId)
        {
            var k = await _apiRequestHelper.PostAsync(SelectedSiparisDetaylarIdList, ApiEndpoints.SiparisControllerCompleteSiparisDetayListByIdListUrl + OdemeTipiId);
            return RedirectToAction("Index");
        }
    }
}

MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!-- Tüm sayfa için bg-dark sınıfını ve metin rengini text-light olarak ayarlıyoruz -->
<div class="text-light min-vh-100 d-flex flex-column align-items-center justify-content-center">
    <h1 class="display-4">VTYS Proje Ödevi</h1>
    <h2 class="display-4">Restaurant Yönetim Sistemi</h2>
    <br />
    <span class="display-12">Hazırlayanlar: Metehan Öztürk, Yavuz Selim İlhan</span>
    <span class="display-12">Öğrenci Numaraları: B231210061, B231210382</span>
    <br />
    <span class="display-12">Api Url -> </span>
    <a href="@ViewBag.url" target="_blank" class="text-light">@ViewBag.url</a>
</div>

MVC/Views/Masa/Details.cshtml
@model Domain.masa.Masa

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Masa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MasaNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MasaNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Kapasite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Kapasite)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Durum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Durum)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "_Edit", Model) |
    <a asp-action="Index">Back to List</a>
</div>

MVC/Views/Masa/Index.cshtml
@model IEnumerable<Domain.masa.Masa>

@{
    ViewData["Title"] = "View";
}

<script src="~/js/siparis.js"></script>
<link rel="stylesheet" href="~/css/masaIndex.css" />
<h1 class="text-center mb-4">Masa Durumları</h1>

<p>
    <a class="btn btn-info btn-sm" asp-action="_Create">Yeni Masa Ekle</a>
</p>

<div class="row g-4">
    @foreach (var item in Model)
    {
        var masaClass = item.Durum ? "yesil" : "kirmizi";  // Durumuna göre renk sınıfı belirle
        <div class="col-md-3">
            <div class="card @masaClass shadow-sm rounded">
                <div class="card-body">
                    <h5 class="card-title">Masa No: @item.MasaNo</h5>
                    <p class="card-text">Kapasite: @item.Kapasite</p>
                    <div class="d-flex justify-content-between">
                        <div>
                            @Html.ActionLink("Düzenle", "_Edit", new { id = item.Id }, new { @class = "btn btn-warning btn-sm" }) |
                            @Html.ActionLink("Detaylar", "Details", new { id = item.Id }, new { @class = "btn btn-info btn-sm" }) |
                            @Html.ActionLink("Sil", "_Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-sm" })
                        </div>
                    </div>
                     <div class="d-flex justify-content-between mt-3">
                        @if(masaClass == "yesil")
                        {
                            <button class="btn btn-light btn-sm siparis-ekle" data-id="@item.Id">Sipariş Ekle</button>
                        }
                        else
                        {
                            <button class="btn btn-light btn-sm odeme-yap" data-id="@item.Id">Ödeme Yap</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
</div>

<div class="pagination mt-4 d-flex justify-content-center">
    @if (ViewBag.CurrentPage > 1)
    {
        <a class="btn btn-light" href="@Url.Action("Index", new { page = ViewBag.CurrentPage - 1 })">Önceki</a>
    }
    @for (int i = 1; i <= ViewBag.TotalPages; i++)
    {
        <a class="btn btn-light" href="@Url.Action("Index", new { page = i })">@i</a>
    }
    @if (ViewBag.CurrentPage < ViewBag.TotalPages)
    {
        <a class="btn btn-light" href="@Url.Action("Index", new { page = ViewBag.CurrentPage + 1 })">Sonraki</a>
    }
</div>

<div id="siparisModalContainer"></div>
<div id="musteriEkleModalContainer"></div>
<div id="odemeYapModalContainer"></div>

<script>
    const odemeYapButtons = document.querySelectorAll(".odeme-yap");
    odemeYapButtons.forEach(button => {
        button.addEventListener("click", function () {
            const masaId = this.getAttribute("data-id");
    
            // Fetch API ile controller'a istek gönder
            fetch(`/Masa/_OdemeYap/${masaId}`)
                .then(response => response.text())
                .then(data => {
                    // Partial view'i modala yerleştir
                    document.getElementById("odemeYapModalContainer").innerHTML = data;
                    // Modalı göster
                    const odemeModal = new bootstrap.Modal(document.getElementById("odemeYapModal"));
                    odemeModal.show();
                    addEventListenersToModal();
                })
                .catch(error => {
                    alert("Bir hata oluştu!");
                });
        });
    });
</script>

MVC/Views/Masa/_Create.cshtml
@model Domain.masa.Masa

@{
    ViewData["Title"] = "_Create";
}

<h1>Create New Masa</h1>

<h4>Masa</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div class="form-group">
                <label asp-for="MasaNo" class="control-label"></label>
                <input asp-for="MasaNo" class="form-control" />
                <span asp-validation-for="MasaNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kapasite" class="control-label"></label>
                <input asp-for="Kapasite" class="form-control" />
                <span asp-validation-for="Kapasite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MVC/Views/Masa/_Delete.cshtml
@model Domain.masa.Masa

<div class="modal fade" id="ModalDelete" tabindex="-1" aria-labelledby="ModalDeleteLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title">Are you sure you want to delete this?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <h4>Masa</h4>
                <hr />
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Id)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Id)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.MasaNo)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.MasaNo)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Kapasite)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Kapasite)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Durum)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Durum)
                    </dd>
                </dl>

                <form asp-action="Delete" method="post">
                    <input type="hidden" name="Id" value="@Model.Id" />
                    <input type="submit" value="Delete" class="btn btn-danger" /> |
                    <a asp-action="Index">Back to List</a>
                </form>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Kapat</button>
                <button type="button" class="btn btn-primary" id="btnModalSave" data-save="modal-create">Oluştur</button>
            </div>
        </div>
    </div>
</div>

MVC/Views/Masa/_Edit.cshtml
@model Domain.masa.Masa

@{
    ViewData["Title"] = "_Edit";
}

<h1>_Edit</h1>

<h4>Masa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MasaNo" class="control-label"></label>
                <input asp-for="MasaNo" class="form-control" />
                <span asp-validation-for="MasaNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kapasite" class="control-label"></label>
                <input asp-for="Kapasite" class="form-control" />
                <span asp-validation-for="Kapasite" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Durum" /> @Html.DisplayNameFor(model => model.Durum)
                </label>
            </div>
            <input type="hidden" name="ID" value="@Model.Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/Views/Masa/_OdemeYap.cshtml
@model List<Domain.siparisdetay.SiparisDetay>

<div class="modal fade" id="odemeYapModal" tabindex="-1" role="dialog" aria-labelledby="odemeYapModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="odemeYapModalLabel">Ödeme Yap</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="odemeForm" asp-controller="Masa" asp-action="OdemeYap" method="post">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th><input type="checkbox" id="selectAll" /></th>
                                    <th>Ürün</th>
                                    <th>Adet</th>
                                    <th>Birim Fiyat</th>
                                    <th>Toplam</th>
                                </tr>
                            </thead>
                            <tbody>
                                @for (int i = 0; i < Model.Count; i++)
                                {
                                    <tr>
                                        <td>
                                            <input type="checkbox" name="SelectedSiparisDetaylarIdList" value="@Model[i].Id" />
                                        </td>
                                        <td>@Model[i].Menu.Ad</td>
                                        <td>@Model[i].Adet</td>
                                        <td>@Model[i].Menu.Fiyat ₺</td>
                                        <td>@(Model[i].Adet * Model[i].Menu.Fiyat) ₺</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        <div class="form-group">
                            <label for="OdemeTipi">Ödeme Tipi</label>
                            <select name="OdemeTipiId" id="OdemeTipi" required class="form-control">
                                <option value="">Ödeme Tipi Seçiniz</option>
                                @foreach (var odemeTipi in ViewBag.OdemeTipleri)
                                {
                                    <option value="@odemeTipi.Id">@odemeTipi.Ad</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="d-flex justify-content-between">
                        <span id="totalAmount" class="fw-bold">Toplam: 0,00 TL</span>
                        <button type="submit" class="btn btn-primary">Ödeme Yap</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

MVC/Views/Masa/_SiparisEkle.cshtml
@model Domain.masa.Masa

<div class="modal fade" id="siparisModal" tabindex="-1" role="dialog" aria-labelledby="siparisModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="siparisModalLabel">Sipariş Ekle - Masa No: @Model.MasaNo</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Form post etmek için gerekli action ve method -->
                <form id="siparisForm" asp-controller="Masa" asp-action="CreateSiparis" method="post">
                    <input type="hidden" name="MasaID" value="@Model.Id" />
                    <!-- Müşteri Seçimi -->
                    <div class="mb-3">
                        <label for="MusteriID" class="form-label">Müşteri</label>
                        <select class="form-control" id="MusteriID" name="MusteriID" required>
                            <option value="">Müşteri Seçiniz</option>
                            @foreach (var musteri in ViewBag.Musteriler)
                            {
                                <option value="@musteri.Id">@musteri.Ad @musteri.Soyad</option>
                            }
                        </select>
                        <button id="btnCreateMusteri" onclick="renderCreateMusteriModal()" class="btn btn-info mt-2" type="button">Müşteri Ekle</button>
                    </div>

                    <!-- Personel Seçimi -->
                    <div class="mb-3">
                        <label for="PersonelID" class="form-label">Personel</label>
                        <select class="form-control" id="PersonelID" name="PersonelID" required>
                            <option value="">Personel Seçiniz</option>
                            @foreach (var personel in ViewBag.Personeller)
                            {
                                <option value="@personel.Id">@personel.Ad @personel.Soyad</option>
                            }
                        </select>
                    </div>

                    <!-- Sipariş Detayları -->
                    <h5>Sipariş Detayları</h5>
                    <div id="siparisDetayContainer">
                        <!-- İlk Sipariş Detay Alanı -->
                        <div class="row mb-3 siparis-detay">
                            <div class="col-md-6">
                                <label for="MenuID" class="form-label">Menu</label>
                                <select class="form-control" name="SiparisDetaylar[0].MenuID" required>
                                    <option value="">Menü Seçiniz</option>
                                    @foreach (var menu in ViewBag.Menuler)
                                    {
                                        <option value="@menu.Id">@menu.Ad - @menu.Fiyat ₺</option>
                                    }
                                </select>
                            </div>
                            <div class="col-md-4">
                                <label for="Adet_1" class="form-label">Adet</label>
                                <input type="number" class="form-control" name="SiparisDetaylar[0].Adet" min="1" required />
                            </div>
                            <div class="col-md-2 d-flex align-items-end">
                                <button type="button" onclick="removeSiparisDetay(this)" class="btn btn-danger remove-detay">Sil</button>
                            </div>
                        </div>
                    </div>
                    <button type="button" onclick="addSiparisDetay()" class="btn btn-secondary mb-3" id="addDetay">Sipariş Detay Ekle</button>
                    <br />

                    <!-- Sipariş Ekle Butonu -->
                    <button type="submit" class="btn btn-primary">Siparişi Ekle</button>
                </form>
            </div>
        </div>
    </div>
</div>

MVC/Views/Masa/_musteriEkle.cshtml
@model Domain.musteri.Musteri

<div class="modal fade" id="createMusteriModal" tabindex="-1" role="dialog" aria-labelledby="createMusteriModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createMusteriModalLabel">Müşteri Ekle</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="siparisForm" asp-controller="Masa" asp-action="CreateMusteri" method="post">
                    <div class="mb-3">
                        <label for="Ad" class="form-label">Müşteri Adı</label>
                        <input type="text" id="Ad" name="Ad" class="form-control" />
                    </div>
                    
                    <div class="mb-3">
                        <label for="Soyad" class="form-label">Müşteri Soyadı</label>
                        <input type="text" id="Soyad" name="Soyad" class="form-control" />
                    </div>
                    
                    <div class="mb-3">
                        <label for="Telefon" class="form-label">Müşteri Telefon</label>
                        <input type="tel" id="Telefon" name="Telefon" class="form-control" />
                    </div>

                    <!-- Müşteri Ekle Butonu -->
                    <button type="submit" class="btn btn-primary">Müşteri Ekle</button>
                </form>
            </div>
        </div>
    </div>
</div>

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <!-- Navbar'ı koyu tema ve beyaz yazılarla yapılandırmak için navbar-dark ve bg-dark sınıflarını kullanıyoruz -->
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VTYS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Giriş Sayfası</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Masa" asp-action="Index">Masa Yönetimi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Masa" asp-action="Index">Masa</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>